# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoUserAccount.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ai_Dialog(object):
    def setupAi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 539)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 170, 251, 111))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(60, 40, 621, 471))
        self.groupBox.setObjectName("groupBox")
        self.spinBoxCard = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxCard.setGeometry(QtCore.QRect(50, 0, 42, 22))
        self.spinBoxCard.setObjectName("spinBoxCard")
        self.lineEditFunds = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditFunds.setGeometry(QtCore.QRect(160, 130, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditFunds.setFont(font)
        self.lineEditFunds.setReadOnly(True)
        self.lineEditFunds.setObjectName("lineEditFunds")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditAccountNumber = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAccountNumber.setGeometry(QtCore.QRect(110, 80, 471, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditAccountNumber.setFont(font)
        self.lineEditAccountNumber.setDragEnabled(False)
        self.lineEditAccountNumber.setReadOnly(True)
        self.lineEditAccountNumber.setObjectName("lineEditAccountNumber")
        self.userNameLabel = QtWidgets.QLabel(self.groupBox)
        self.userNameLabel.setGeometry(QtCore.QRect(100, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.userNameLabel.setFont(font)
        self.userNameLabel.setText("")
        self.userNameLabel.setObjectName("userNameLabel")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 350, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEditEnterValue = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditEnterValue.setGeometry(QtCore.QRect(110, 210, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditEnterValue.setFont(font)
        self.lineEditEnterValue.setObjectName("lineEditEnterValue")
        self.lineEditNumberToSend = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditNumberToSend.setGeometry(QtCore.QRect(150, 250, 471, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditNumberToSend.setFont(font)
        self.lineEditNumberToSend.setDragEnabled(False)
        self.lineEditNumberToSend.setReadOnly(False)
        self.lineEditNumberToSend.setObjectName("lineEditNumberToSend")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.spinBoxSelectCard = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxSelectCard.setGeometry(QtCore.QRect(110, 180, 42, 22))
        self.spinBoxSelectCard.setObjectName("spinBoxSelectCard")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButtonAddCard = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonAddCard.setGeometry(QtCore.QRect(20, 390, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAddCard.setFont(font)
        self.pushButtonAddCard.setObjectName("pushButtonAddCard")
        self.pushButtonSend = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonSend.setGeometry(QtCore.QRect(20, 280, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Card:"))
        self.label_3.setText(_translate("Dialog", "Available funds:"))
        self.label.setText(_translate("Dialog", "User:"))
        self.label_2.setText(_translate("Dialog", "Number:"))
        self.label_8.setText(_translate("Dialog", "Add a new card:"))
        self.label_7.setText(_translate("Dialog", "Account number:"))
        self.label_6.setText(_translate("Dialog", "Enter value:"))
        self.pushButtonAddCard.setText(_translate("Dialog", "New Card"))
        self.pushButtonSend.setText(_translate("Dialog", "Send"))
        self.label_5.setText(_translate("Dialog", "Select card:"))
        self.label_4.setText(_translate("Dialog", "Transfer money:"))
        self.pushButton.setText(_translate("Dialog", "Click to Continue"))
